[project]
authors = ["ET:Legacy"]
channels = ["conda-forge"]
description = "Release note renderer"
name = "release-notes"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
"python" = "3.13.0"
"pyyaml" = "6.0.2"
"jinja2" = "3.1.4"
